#!/usr/bin/env python
import rospy
from sensor_msgs.msg import NavSatFix

def callback(data):
    print(data)

def listener():
        try:
            rospy.init_node('gps', anonymous=True)
            rospy.Subscriber("fix", NavSatFix, callback)
            rospy.spin()
        except KeyboardInterrupt:
            pass


if __name__ == '__main__':
    listener()
